#!/bin/bash

cd solvers/passiveGDHFoam
	wmake
cd ../passiveGDHExpFoam
	wmake
cd ../passiveFoxASMFoam
	wmake
cd ../passiveLaminarFoam
	wmake
cd ../passiveTransGDHFoam
	wmake
cd ../passiveTransGDHExpFoam
	wclean
cd ../passiveTransLaminarFoam
	wmake

