#!/bin/bash

cd solvers/passiveGDHFoam
	wclean
cd ../passiveGDHExpFoam
	wclean
cd ../passiveFoxASMFoam
	wclean
cd ../passiveLaminarFoam
	wclean
cd ../passiveTransGDHFoam
	wclean
cd ../passiveTransGDHExpFoam
	wclean
cd ../passiveTransLaminarFoam
	wclean

